### ISSUE TITLE
Sync/standardize/document environment variables for all backend gateway services

### ISSUE THREAD

**Issue by JoeCap08055** [AmplicaLabs/gateway#158]
As a developer, I want clear documentation regarding the available options for configuring a service via the environment. When multiple related services each have environment variables that service the same purpose, they should be consistently named. A sample `.env.template` file or README documentation should document all available environment variables, their purpose, range of values, and whether required or optional.

- [x] AmplicaLabs/reconnection-service#96
- [x] AmplicaLabs/graph-service#51
- [x] AmplicaLabs/content-publishing-service#86
- [x] AmplicaLabs/content-watcher-service#29
- [x] AmplicaLabs/account-service#38
