### ISSUE TITLE
Post Mono Repo TODO

### ISSUE THREAD

**Issue by wilwade** [AmplicaLabs/gateway#252]
- [x] #271
- [x] #298
- [x] #262
- [x] #260
- [x] #300
- [x] Add link to each api in docs
- [x] Fix release pipelines and publish all containers

**Comment by mattheworris** [comment]
- [ ] Add link to each api in docs
- The README.md was updated and the OpenAPI specs are correctly published.
